name: Mobile App Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Mobile App Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Run tests with Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            adb devices
            
            adb wait-for-device

            # wait for full boot
            while [ "$(adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ]; do
              sleep 5
            done

            echo "Emulator ready"

            npx appium &

            npx wdio run ./wdio.conf.js --spec test/specs/signup.test.js

            npx wdio run ./wdio.conf.js --spec test/specs/golf.test.js